author: "https://www.michaelhartl.com/"
enabled_locales: ["en", "vi"]
image_size: 200
learn_enough_web: "https://www.learnenough.com/"
maximum_email_length: 255
maximum_name_length: 50
minimum_password_length: 6
rails: "https://rubyonrails.org/"
rails_book: "https://www.railstutorial.org/book"
rails_contact: "https://www.railstutorial.org/contact"
rails_help: "https://www.railstutorial.org/help"
rails_news: "https://news.railstutorial.org/"
rails_tutorial: "https://www.railstutorial.org/"
screencast_web: "https://screencasts.railstutorial.org/"
valid_email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
